version: '3.8'

services:
  supabase-mcp-http:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}
      - SUPABASE_READ_ONLY=${SUPABASE_READ_ONLY:-false}
      - SUPABASE_FEATURES=${SUPABASE_FEATURES:-docs,account,database,debugging,development,functions,branching}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
